application: tweetc-app
version: 1
runtime: python
api_version: 1

inbound_services:
- mail

handlers:
- url: /favicon.ico
  static_files: static/images/favicon.ico
  upload: static/images/favicon.ico    
    
- url: /static
  static_dir: static

- url: /_ah/mail/.+ 
  script: main.py 
  
- url: /.*
  script: main.py

  



